name: $(Date:3.5.0)$(Rev:.r)
trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: 'allure-csharp.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: bleddynrichards.Assembly-Info-Task.Assembly-Info-NetCore.Assembly-Info-NetCore@2
  displayName: 'Set Assembly Manifest Data'
  inputs:
    GeneratePackageOnBuild: true
    VersionNumber: '$(Build.BuildNumber)'
    FileVersionNumber: '$(Build.BuildNumber)'
    InformationalVersion: '$(Build.BuildNumber)'
    PackageVersion: '$(Build.BuildNumber)'
- task: NuGetToolInstaller@1
  enabled: true
  displayName: 'Use NuGet'
  inputs:
    checkLatest: true
- task: NuGetCommand@2
  enabled: true
  displayName: 'NuGet restore'
  inputs:
    restoreSolution: '$(solution)'
    restoreDirectory: packages
- task: DotNetCoreCLI@2
  displayName: Test Allure.Commons
  inputs:
    command: 'test'
    projects: '**/Allure.Commons.Tests.csproj'
    arguments: '-c $(buildConfiguration) --no-restore'

- task: DotNetCoreCLI@2
  displayName: Run SpecFlow features
  inputs:
    command: 'test'
    projects: '**/Allure.Features.csproj'
    arguments: '-c $(buildConfiguration) --no-restore'
    publishTestResults: false
    
- task: DotNetCoreCLI@2
  displayName: Test SpecFlow plugin
  inputs:
    command: 'test'
    projects: '**/Allure.SpecFlowPlugin.Tests.csproj'
    arguments: '-c $(buildConfiguration) --no-restore'
    publishTestResults: true