name: $(Date:3.5.0)$(Rev:.r)
trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: 'allure-csharp.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  isMaster: $[eq(variables['Build.SourceBranch'], 'refs/heads/master')]

steps:
- task: bleddynrichards.Assembly-Info-Task.Assembly-Info-NetCore.Assembly-Info-NetCore@2
  enabled: true
  displayName: 'Set Assembly Manifest Data'
  inputs:
    GeneratePackageOnBuild: true
    VersionNumber: '$(Build.BuildNumber)'
    FileVersionNumber: '$(Build.BuildNumber)'
    InformationalVersion: '$(Build.BuildNumber)'
    PackageVersion: '$(Build.BuildNumber)'
    
- task: NuGetToolInstaller@1
  enabled: true
  displayName: 'Use NuGet'
  inputs:
    checkLatest: true

- task: NuGetCommand@2
  enabled: true
  displayName: 'NuGet restore'
  inputs:
    restoreSolution: '$(solution)'
    restoreDirectory: packages

- task: DotNetCoreCLI@2
  enabled: true
  displayName: Build $(solution)
  inputs:
    command: 'build'
    projects: '$(solution)'
    arguments: '-c $(buildConfiguration) --no-restore /p:PackageOutputPath=$(Build.ArtifactStagingDirectory)'

- task: DotNetCoreCLI@2
  enabled: true
  displayName: Run tests
  inputs:
    command: 'test'
    projects: |
      **/Allure.Commons.Tests.csproj
      **/Allure.SpecFlowPlugin.Tests.csproj
    arguments: '-c $(buildConfiguration) --no-restore'
    publishTestResults: true
  
- task: PublishBuildArtifacts@1
  enabled: true
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'

- task: NuGetCommand@2
  enabled: true
  condition: and(succeeded(), eq(variables.isMaster, true))
  displayName: Push packages
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.*nupkg'
    nuGetFeedType: 'external'
    publishFeedCredentials: 'AlexBakanov'

- task: AzureCLI@2
  enabled: true
  displayName: 'Generate Allure report'
  condition: and(succeeded(), eq(variables.isMaster, true))
  inputs:
    azureSubscription: 'AlexB (3b78fad5-1e95-4a49-87b8-6a11dcc91996)'
    scriptType: 'pscore'
    scriptLocation: 'inlineScript'
    inlineScript: |
      mkdir allure-results/history
      az storage blob download-batch --account-name allure --account-key $(AZURE_KEY) -s '$web' -d allure-results/ --pattern history/*
      npm install allure-commandline -g
      allure generate
      az storage blob upload-batch --account-name allure --account-key $(AZURE_KEY) -d '$web' -s ./allure-report
    workingDirectory: 'Allure.Features/bin/netcoreapp3.1'
